//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.18 at 03:26:57 PM PST 
//


package com.reactiveworks.jaxb.trial;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for entityaccessconfigtype.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="entityaccessconfigtype">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SQL"/>
 *     &lt;enumeration value="HAZALCAST"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "entityaccessconfigtype")
@XmlEnum
public enum Entityaccessconfigtype {

    SQL,
    HAZALCAST;

    public String value() {
        return name();
    } 

    public static Entityaccessconfigtype fromValue(String v) {
        return valueOf(v);
    }

}
